/*
 * Generated by Gemini (AI Model)
 * Date: March 2026
 * Description: A single-file QML calculator implementation.
 * Source: https://gemini.google.com/share/4e9d0166fa57
 * Note: This layout file had to be generated because my Qt Creator
 *       crashes upon adding any element to it -_-
 */

import QtQuick
import QtQuick.Controls
import QtQuick.Layouts

Window {
    width  : 640
    height : 480
    visible: true
    color  : "#666666"
    title  : qsTr("Simple Calculator :D")

    property string display: "0"

    ColumnLayout {
        anchors.fill     : parent
        anchors.margins  : 25
        anchors.topMargin: 75
        spacing          : 50

        // Result Display
        Rectangle {
            Layout.fillWidth      : true
            Layout.preferredHeight: 70
            color                 : "#274e13"

            Rectangle {
                anchors.bottom: parent.bottom
                width         : parent.width
                height        : 5
                color         : "#000000"
            }

            Text {
                anchors.right         : parent.right
                anchors.verticalCenter: parent.verticalCenter
                anchors.rightMargin   : 15
                text                  : display
                color                 : "white"
                font.family           : "DepartureMono"
                font.pixelSize        : 36
                font.weight           : Font.Bold
            }
        }

        // Button Grid
        GridLayout {
            Layout.fillWidth : true
            Layout.fillHeight: true
            rows             : 5
            columns          : 4
            rowSpacing       : 10
            columnSpacing    : 10

            // Helper component to create buttons
            component CalcButton : Button {
                property alias bgColor: bg.color

                Layout.fillWidth : true
                Layout.fillHeight: true
                flat             : true
                hoverEnabled     : true

                Rectangle {
                    width       : parent.width + 5
                    height      : parent.height + 5
                    color       : "#000000"
                }

                Rectangle {
                    id          : bg
                    anchors.fill: parent
                    color       : "#bf9000"
                }

                contentItem: Text {
                    text               : parent.text
                    font.family        : "DepartureMono"
                    font.pixelSize     : 24
                    font.weight        : Font.ExtraBold
                    color              : "white"
                    horizontalAlignment: Text.AlignHCenter
                    verticalAlignment  : Text.AlignVCenter
                }
            }

            // The top row except the '+' operand
            CalcButton {
                text: "Off"
                bgColor: "#cf2a27"

                ToolTip {
                    delay: 100
                    text: "Exit the program"
                }
            }
            CalcButton {
                text: "CE"
                bgColor: "#597eaa"

                ToolTip {
                    delay: 100
                    text: "Clear whole equation"
                }
            }
            CalcButton {
                text: "C"
                bgColor: "#597eaa"

                ToolTip {
                    delay: 100
                    text: "Clear current input"
                }
            }

            // The numpad with the rest of buttons
                                                                                                                                                      CalcButton { text: "÷"; bgColor: "#6fa8dc" }
            CalcButton { text: "7"  ;                    } CalcButton { text: "8" ;                    } CalcButton { text: "9";                    } CalcButton { text: "-"; bgColor: "#6fa8dc" }
            CalcButton { text: "4"  ;                    } CalcButton { text: "5" ;                    } CalcButton { text: "6";                    } CalcButton { text: "×"; bgColor: "#6fa8dc" }
            CalcButton { text: "1"  ;                    } CalcButton { text: "2" ;                    } CalcButton { text: "3";                    } CalcButton { text: "/"; bgColor: "#6fa8dc" }
            CalcButton { text: "+/-"; bgColor: "#93c47d" } CalcButton { text: "0" ;                    } CalcButton { text: ","; bgColor: "#6aa84f" } CalcButton { text: "="; bgColor: "#009e0f" }
        }
    }
}
