/*
 * Generated by Gemini (AI Model)
 * Date: March 2026
 * Description: A single-file QML calculator implementation.
 * Source: https://gemini.google.com/share/4e9d0166fa57
 * Note: This layout file had to be generated because my Qt Creator
 *       crashes upon adding any element to it -_-
 */

import QtQuick
import QtQuick.Controls
import QtQuick.Layouts

import CalculatorComponent 1.0

Window {
    width  : 640
    height : 480
    visible: true
    color  : "#666666"
    title  : qsTr("Simple Calculator :D")

    property string display: "0"

    Calculator {
        id: calculator

        onDisplayedNumberChanged: function(newNumber) {
            display = newNumber;
        }
        onErrorOccurred: {
            display = "ERROR ( °□°)";
        }
    }

    ColumnLayout {
        anchors.fill     : parent
        anchors.margins  : 25
        anchors.topMargin: 75
        spacing          : 50

        // Result Display
        Rectangle {
            Layout.fillWidth      : true
            Layout.preferredHeight: 70
            color                 : "#274e13"

            Rectangle {
                anchors.bottom: parent.bottom
                width         : parent.width
                height        : 5
                color         : "#000000"
            }

            Text {
                anchors.right         : parent.right
                anchors.verticalCenter: parent.verticalCenter
                anchors.rightMargin   : 15
                text                  : display
                color                 : "white"
                font.family           : "DepartureMono"
                font.pixelSize        : 36
                font.weight           : Font.Bold
            }
        }

        // Button Grid
        GridLayout {
            Layout.fillWidth : true
            Layout.fillHeight: true
            rows             : 5
            columns          : 4
            rowSpacing       : 10
            columnSpacing    : 10

            // Base component to create buttons
            component CalcButton : Button {
                property alias bgColor: bg.color;

                Layout.fillWidth : true
                Layout.fillHeight: true
                flat             : true
                hoverEnabled     : true

                // Adding some shadow
                Rectangle {
                    width       : parent.width + 5
                    height      : parent.height + 5
                    color       : "#000000"
                }

                // Adding some background
                Rectangle {
                    id          : bg
                    anchors.fill: parent
                    color       : "#000000"
                }

                contentItem: Text {
                    text               : parent.text
                    font.family        : "DepartureMono"
                    font.pixelSize     : 24
                    font.weight        : Font.ExtraBold
                    color              : "white"
                    horizontalAlignment: Text.AlignHCenter
                    verticalAlignment  : Text.AlignVCenter
                }
            }


            // Base number buttons' component
            component NumberButton : CalcButton {
                bgColor: "#bf9000"

                // Setting shortcut to button's symbol by default
                Shortcut {
                    sequence   : text
                    onActivated: click();
                }

                // Adding digit upon clicking
                onClicked: calculator.addDigit(Number(text));
            }

            // Base operand buttons' component
            component OperandButton : CalcButton {
                bgColor: "#6fa8dc"

                // Setting shortcut to button's symbol by default
                Shortcut {
                    sequence   : text
                    onActivated: click();
                }

                // Setting operand to button's symbol upon clicking
                onClicked: calculator.setOperand(text);
            }

            // Buttons' definitions
            // [First Row] (top)
            CalcButton {
                id     : exitButton
                text   : "Off"
                bgColor: "#cf2a27"

                ToolTip {
                    delay: 100
                    text : "Exit the program"
                }

                Shortcut {
                    sequence   : "ESC"
                    onActivated: exitButton.click();
                }

                onClicked: close();
            }
            CalcButton {
                id     : resetButton
                text   : "CE"
                bgColor: "#597eaa"

                ToolTip {
                    delay: 100
                    text : "Clear whole equation"
                }

                Shortcut {
                    sequence   : "Shift+Backspace"
                    onActivated: resetButton.click();
                }

                onClicked: calculator.clear(true);
            }
            CalcButton {
                id     : clearButton
                text   : "C"
                bgColor: "#597eaa"

                ToolTip {
                    delay: 100
                    text : "Clear current input"
                }

                Shortcut {
                    sequence   : "Backspace"
                    onActivated: clearButton.click();
                }

                onClicked: calculator.clear(false);
            }
            OperandButton { text: "+" }

            // [Second Row]
            NumberButton { text: "7" } NumberButton { text: "8" } NumberButton { text: "9" } OperandButton { text: "-" }
            // [Third Row]
            NumberButton { text: "4" } NumberButton { text: "5" } NumberButton { text: "6" } OperandButton { text: "*" }
            // [Fourth Row]
            NumberButton { text: "1" } NumberButton { text: "2" } NumberButton { text: "3" } OperandButton { text: "/" }

            // [Fifth Row] (bottom)
            OperandButton {
                text: "+/-"
                bgColor: "#93c47d"
            }
            NumberButton { text: "0" }
            OperandButton {
                text: ","
                bgColor: "#6aa84f"
            }
            CalcButton {
                text: "="
                bgColor: "#009e0f"
                onClicked: calculator.calculate();
            }
        }
    }
}
